openapi: "3.1.0"
info:
  title: "airbyte-api"
  version: "1.0.0"
  description: "Programmatically control Airbyte Cloud, OSS & Enterprise."
servers:
- url: "https://api.airbyte.com/v1"
  description: "Airbyte API v1"
paths:
  /connections:
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConnectionCreateRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionResponse"
      operationId: "createConnection"
      x-speakeasy-alias: "createConnection"
      x-speakeasy-group: "Connections"
      summary: "Create a connection"
      x-speakeasy-entity-operation: Connection#create
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionsResponse"
      operationId: "listConnections"
      x-speakeasy-alias: "listConnections"
      x-speakeasy-group: "Connections"
      summary: "List connections"
      x-speakeasy-entity-operation: Connection#list

  /connections/{connectionId}:

    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionResponse"
      operationId: "getConnection"
      x-speakeasy-alias: "getConnection"
      x-speakeasy-group: "Connections"
      summary: "Get Connection details"
      x-speakeasy-entity-operation: Connection#read

    patch:
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ConnectionPatchRequest"
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ConnectionResponse"
      operationId: "patchConnection"
      x-speakeasy-alias: "patchConnection"
      x-speakeasy-group: "Connections"
      summary: "Update Connection details"
      x-speakeasy-entity-operation: Connection#update

    delete:
      responses:
        "2XX":
          description: "The resource was deleted successfully"
        "403":
          description: "Not allowed"
        "404":
          description: "Not found"
      operationId: "deleteConnection"
      x-speakeasy-alias: "deleteConnection"
      x-speakeasy-group: "Connections"
      summary: "Delete a Connection"
      x-speakeasy-entity-operation: Connection#delete

    parameters:
    - name: "connectionId"
      schema:
        format: "UUID"
        type: "string"
      in: "path"
      required: true

components:
  schemas:
    ConnectionCreateRequest:
      required:
      - "sourceId"
      - "destinationId"
      type: "object"
      properties:
        name:
          description: "Optional name of the connection"
          type: "string"
        sourceId:
          format: "uuid"
          type: "string"
        destinationId:
          format: "uuid"
          type: "string"
        configurations:
          $ref: "#/components/schemas/StreamConfigurations"
      x-speakeasy-entity: Connection

    ConnectionPatchRequest:
      type: "object"
      properties:
        name:
          description: "Optional name of the connection"
          type: "string"
      x-speakeasy-entity: Connection

    ConnectionResponse:
      title: "Root Type for ConnectionResponse"
      description: "Provides details of a single connection."
      type: "object"
      required:
      - "connectionId"
      - "name"
      - "sourceId"
      - "destinationId"
      - "createdAt"
      properties:
        connectionId:
          format: "UUID"
          type: "string"
        name:
          type: "string"
        sourceId:
          format: "UUID"
          type: "string"
        destinationId:
          format: "UUID"
          type: "string"
        workspaceId:
          format: "UUID"
          type: "string"
        createdAt:
          format: "int64"
          type: "integer"
        configurations:
          $ref: "#/components/schemas/StreamConfigurations"
      x-speakeasy-entity: Connection

    ConnectionsResponse:
      title: "Root Type for ConnectionsResponse"
      description: ""
      required:
      - "data"
      type: "object"
      properties:
        previous:
          type: "string"
        next:
          type: "string"
        data:
          type: "array"
          items:
            $ref: "#/components/schemas/ConnectionResponse"
          default: []

    StreamConfigurations:
      description: "A list of configured stream options for a connection."
      type: "object"
      properties:
        streams:
          type: "array"
          items:
            $ref: "#/components/schemas/StreamConfiguration"

    StreamConfiguration:
      description: "Configurations for a single stream."
      type: "object"
      required:
      - "name"
      properties:
        name:
          type: "string"
        cursorField:
          type: "array"
          items:
            type: "string"
        primaryKey:
          type: "array"
          items:
            type: "array"
            items:
              type: "string"
    