// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

// ConnectionResponse - Provides details of a single connection.
type ConnectionResponse struct {
	ConnectionID  string  `json:"connectionId"`
	Name          string  `json:"name"`
	SourceID      string  `json:"sourceId"`
	DestinationID string  `json:"destinationId"`
	WorkspaceID   *string `json:"workspaceId,omitempty"`
	CreatedAt     int64   `json:"createdAt"`
	// A list of configured stream options for a connection.
	Configurations *StreamConfigurations `json:"configurations,omitempty"`
}

func (o *ConnectionResponse) GetConnectionID() string {
	if o == nil {
		return ""
	}
	return o.ConnectionID
}

func (o *ConnectionResponse) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *ConnectionResponse) GetSourceID() string {
	if o == nil {
		return ""
	}
	return o.SourceID
}

func (o *ConnectionResponse) GetDestinationID() string {
	if o == nil {
		return ""
	}
	return o.DestinationID
}

func (o *ConnectionResponse) GetWorkspaceID() *string {
	if o == nil {
		return nil
	}
	return o.WorkspaceID
}

func (o *ConnectionResponse) GetCreatedAt() int64 {
	if o == nil {
		return 0
	}
	return o.CreatedAt
}

func (o *ConnectionResponse) GetConfigurations() *StreamConfigurations {
	if o == nil {
		return nil
	}
	return o.Configurations
}
