// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ConnectionPatchRequest struct {
	// Optional name of the connection
	Name *string `json:"name,omitempty"`
}

func (o *ConnectionPatchRequest) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}
