// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// StreamConfiguration - Configurations for a single stream.
type StreamConfiguration struct {
	Name        string     `json:"name"`
	CursorField []string   `json:"cursorField,omitempty"`
	PrimaryKey  [][]string `json:"primaryKey,omitempty"`
}

func (o *StreamConfiguration) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *StreamConfiguration) GetCursorField() []string {
	if o == nil {
		return nil
	}
	return o.CursorField
}

func (o *StreamConfiguration) GetPrimaryKey() [][]string {
	if o == nil {
		return nil
	}
	return o.PrimaryKey
}
